[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
cache_path = 'foundry-cache'
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
solc_version = "0.8.13"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
anvil = "http://127.0.0.1:8454"
goerli = "${GOERLI_RPC_URL}"

[etherscan]
anvil = { key = "" }
goerli = { key = "${ETHERSCAN_API_KEY}" }